### ISSUE TITLE
Please tell me where the course is

### ISSUE THREAD

**Issue by Jayoprell** [geohot/fromthetransistor#15]

**Comment by andrewboldi** [comment]
No.

**Comment by Jayoprell** [comment]
😥

**Comment by andrewboldi** [comment]
lol I don't know either.

**Comment by hotwaterheater** [comment]
There is no course. It's a half started skeleton of a project. Some of the other issues have good recommendations though.

**Comment by andrewboldi** [comment]
ah so it's just like hammer.lol ...?

**Comment by Jayoprell** [comment]
Thanks. 
I've found a book which exactly contains all the contents that this project mentions.

**Comment by andrewboldi** [comment]
Which book are you talking about?

**Comment by Jayoprell** [comment]
The Elements of Computing Systems : Building a Modern Computer from First Principles by Noam Nisan, Shimon Schocken

**Comment by andrewboldi** [comment]
Thankee sire for thine information. I shall commence my studies.

**Comment by Jayoprell** [comment]
You're welcome.

**Comment by jakehemmerle** [comment]
A second edition of the book has been released!

The Elements of Computing Systems : Building a Modern Computer from First Principles by Noam Nisan, Shimon Schocken

Edition differences: The first edition of this popular textbook inspired Nand to Tetris courses in many universities, coding boot camps, hacker clubs, and online course platforms. This second edition has been extensively revised. It has been restructured into two distinct parts—part I, Hardware, and part II, Software—with six projects in each part. All chapters and projects have been rewritten, with an emphasis on separating abstraction from implementation, and many new sections, figures, and examples have been added. Substantial new appendixes offer focused presentation on technical and theoretical topics.

https://www.amazon.com/Elements-Computing-Systems-second-Principles-ebook/dp/B084V7R8PT/
