### ISSUE TITLE
This or Nand2Tetris?

### ISSUE THREAD

**Issue by blacknand** [geohot/fromthetransistor#27]
I did week 1 of this and then got completely stuck on just trying to get anything running with Verilator. I looked into this course to see if there are any existing resources online for it and a lot of people seem to agree to do Nand2Tetris instead, which I think is a good idea. I want to do this because I am a huge fan of George but this just seems way too advanced, time consuming and complicated for me right now. 

Is it a good idea to do Nand2Tetris, and then come back to this?

**Comment by shaolin-peanut** [comment]
The point is to learn stuff in whichever way works best for you.

I recommend you join the discord linked on this website https://learnaifromscratch.github.io/ and just scout for ressources related to computer architecture, systems, OS, etc. 
The amount of free courses shared there is gigantic, the hard part is choosing what's the best next step with you given your current understanding/experience

nand2tetris is probably a very good thing to do

Good luck, and send updates here!

**Comment by blacknand** [comment]
Thanks for replying. I am going to join that discord and then start Nand2Tetris on 10th May when I have finished my final exams and can start, I'll make sure to send updates!
